/**
 * @file web_content.c
 * @brief Embedded HTML/CSS/JS content for web UI
 */

#include "web_content.h"
#include <string.h>

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>CT-HMI Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;color:#333;line-height:1.6}"
".container{max-width:600px;margin:0 auto;padding:20px}"
"h1{text-align:center;margin-bottom:20px;color:#2196F3;font-size:1.5rem}"
".section{background:#fff;border-radius:8px;padding:20px;margin-bottom:15px;box-shadow:0 2px 4px rgba(0,0,0,0.1)}"
".section h2{font-size:1rem;color:#666;margin-bottom:15px;padding-bottom:10px;border-bottom:1px solid #eee}"
".form-group{margin-bottom:15px}"
".form-group label{display:block;font-size:.875rem;font-weight:500;margin-bottom:5px;color:#555}"
".form-group input,.form-group select{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:6px;font-size:1rem;transition:border-color .2s}"
".form-group input:focus,.form-group select:focus{outline:none;border-color:#2196F3}"
".form-row{display:flex;gap:10px}"
".form-row .form-group{flex:1}"
".input-with-btn{display:flex;gap:10px}"
".input-with-btn input,.input-with-btn select{flex:1}"
".input-with-btn button{padding:10px 15px;white-space:nowrap}"
"button{background:#2196F3;color:#fff;border:none;border-radius:6px;padding:12px 20px;font-size:1rem;cursor:pointer;transition:background .2s}"
"button:hover{background:#1976D2}"
"button:disabled{background:#ccc;cursor:not-allowed}"
".btn-secondary{background:#757575}"
".btn-secondary:hover{background:#616161}"
".btn-full{width:100%;margin-top:10px}"
".collapsible h2{cursor:pointer;display:flex;justify-content:space-between;align-items:center}"
".collapsible h2 .toggle{font-size:.75rem;color:#999}"
".collapsible.collapsed .section-content{display:none}"
".checkbox-group{display:flex;align-items:center;gap:8px}"
".checkbox-group input[type=checkbox]{width:auto}"
".cb-row{display:flex;gap:15px}.cbl{display:flex;align-items:center;gap:4px;font-size:.875rem}.cbl input{width:auto}"
".ct-gains{display:flex;gap:10px}"
".ct-gains input{flex:1;text-align:center}"
".status-bar{background:#333;color:#fff;padding:12px 15px;border-radius:6px;font-size:.875rem;display:flex;justify-content:space-between}"
".status-bar .ok{color:#4CAF50}"
".status-bar .warn{color:#FF9800}"
".alert{padding:12px 15px;border-radius:6px;margin-bottom:15px;font-size:.875rem}"
".alert-success{background:#E8F5E9;color:#2E7D32;border:1px solid #A5D6A7}"
".alert-error{background:#FFEBEE;color:#C62828;border:1px solid #EF9A9A}"
".hidden{display:none!important}"
".loading{display:inline-block;width:16px;height:16px;border:2px solid #fff;border-radius:50%;border-top-color:transparent;animation:spin 1s linear infinite;margin-right:8px}"
"@keyframes spin{to{transform:rotate(360deg)}}"
".password-toggle{position:relative}"
".password-toggle input{padding-right:40px}"
".password-toggle button{position:absolute;right:5px;top:50%;transform:translateY(-50%);background:none;border:none;padding:5px;color:#666;font-size:1.2rem}"
".password-toggle button:hover{color:#333;background:none}"
"@media(max-width:480px){.form-row{flex-direction:column;gap:0}.ct-gains{flex-direction:column}}"
"</style>"
"</head>"
"<body>"
"<div class=\"container\">"
"<h1>CT-HMI Device Setup</h1>"

"<div id=\"alert\" class=\"alert hidden\"></div>"

"<div class=\"section\">"
"<h2>Device Identity</h2>"
"<div class=\"form-group\">"
"<label for=\"device_id\">Device ID *</label>"
"<input type=\"text\" id=\"device_id\" placeholder=\"DM-004\" maxlength=\"15\" required>"
"</div>"
"<div class=\"form-group\">"
"<label for=\"location\">Location</label>"
"<input type=\"text\" id=\"location\" placeholder=\"Factory-A Line-3\" maxlength=\"31\">"
"</div>"
"</div>"

"<div class=\"section\" id=\"wifi_section\">"
"<h2>WiFi Configuration</h2>"
"<div class=\"form-group\">"
"<label for=\"wifi_ssid\">WiFi Network *</label>"
"<div class=\"input-with-btn\">"
"<select id=\"wifi_ssid\"><option value=\"\">-- Select Network --</option></select>"
"<button type=\"button\" id=\"scan_btn\">Scan</button>"
"</div>"
"</div>"
"<div class=\"form-group password-toggle\">"
"<label for=\"wifi_password\">WiFi Password *</label>"
"<input type=\"password\" id=\"wifi_password\" placeholder=\"Enter WiFi password\">"
"<button type=\"button\" onclick=\"togglePassword('wifi_password',this)\">Show</button>"
"</div>"
"</div>"

"<div class=\"section collapsible collapsed\" id=\"mqtt_section\">"
"<h2 onclick=\"toggleSection('mqtt_section')\">MQTT Configuration <span class=\"toggle\">+</span></h2>"
"<div class=\"section-content\">"
"<div class=\"form-group checkbox-group\">"
"<input type=\"checkbox\" id=\"use_default_mqtt\" checked onchange=\"toggleMqttFields()\">"
"<label for=\"use_default_mqtt\">Use Default Server (recommended)</label>"
"</div>"
"<div id=\"mqtt_fields\" class=\"hidden\">"
"<div class=\"form-group\">"
"<label for=\"mqtt_broker\">Broker Host</label>"
"<input type=\"text\" id=\"mqtt_broker\" value=\"limelight.mvp5464.com\">"
"</div>"
"<div class=\"form-row\">"
"<div class=\"form-group\">"
"<label for=\"mqtt_port\">Port</label>"
"<input type=\"number\" id=\"mqtt_port\" value=\"1883\">"
"</div>"
"<div class=\"form-group\">"
"<label for=\"mqtt_username\">Username</label>"
"<input type=\"text\" id=\"mqtt_username\" value=\"limelightit\">"
"</div>"
"</div>"
"<div class=\"form-group password-toggle\">"
"<label for=\"mqtt_password\">Password</label>"
"<input type=\"password\" id=\"mqtt_password\" value=\"4P5t3XmBhQ6C\">"
"<button type=\"button\" onclick=\"togglePassword('mqtt_password',this)\">Show</button>"
"</div>"
"</div>"
"</div>"
"</div>"

"<div class=\"section collapsible collapsed\" id=\"machine_section\">"
"<h2 onclick=\"toggleSection('machine_section')\">Machine Settings <span class=\"toggle\">+</span></h2>"
"<div class=\"section-content\">"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>State Threshold (kW)</label><input type=\"number\" id=\"active_threshold\" value=\"0.50\" step=\"0.01\" min=\"0.01\" max=\"100\"></div>"
"<div class=\"form-group\"><label>Hysteresis</label><input type=\"number\" id=\"hysteresis_factor\" value=\"0.8\" step=\"0.01\" min=\"0.1\" max=\"1.0\"></div>"
"</div>"
"<div class=\"form-group\"><label>Machine Setup Time (ms)</label><input type=\"number\" id=\"machine_setup_time_ms\" value=\"1000\" step=\"100\" min=\"100\"></div>"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>Voltage (V)</label><input type=\"number\" id=\"voltage_nominal\" value=\"230\" step=\"1\" min=\"100\" max=\"480\"></div>"
"<div class=\"form-group\"><label>Power Factor</label><input type=\"number\" id=\"power_factor\" value=\"0.85\" step=\"0.01\" min=\"0.1\" max=\"1.0\"></div>"
"</div>"
"<div class=\"form-group\"><label>CT Calibration Gains</label><div class=\"ct-gains\">"
"<input type=\"number\" id=\"ct_gain_0\" value=\"1.314\" step=\"0.001\" placeholder=\"A\">"
"<input type=\"number\" id=\"ct_gain_1\" value=\"1.314\" step=\"0.001\" placeholder=\"B\">"
"<input type=\"number\" id=\"ct_gain_2\" value=\"1.314\" step=\"0.001\" placeholder=\"C\">"
"</div></div>"
"</div></div>"

"<div class=\"section collapsible collapsed\" id=\"ct_section\">"
"<h2 onclick=\"toggleSection('ct_section')\">Input Sources <span class=\"toggle\">+</span></h2>"
"<div class=\"section-content\">"
"<div class=\"form-group checkbox-group\"><input type=\"checkbox\" id=\"ignore_open_ct\" checked><label for=\"ignore_open_ct\">Ignore Open CTs</label></div>"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>State Detection</label><select id=\"state_source\">"
"<option value=\"0\">CT</option><option value=\"1\">Signal Based</option></select></div>"
"<div class=\"form-group\"><label>Signal Logic</label><select id=\"signal_logic\">"
"<option value=\"0\">NO</option><option value=\"1\">NC</option></select></div>"
"</div>"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>State CT Mode</label><select id=\"state_ct_phase_mode\">"
"<option value=\"0\">One Phase (A)</option><option value=\"1\">Three Phase</option></select></div>"
"<div class=\"form-group\"><label>Energy CT Mode</label><select id=\"energy_ct_phase_mode\">"
"<option value=\"0\">One Phase (A)</option><option value=\"1\">Three Phase</option></select></div>"
"</div>"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>Idle Stabilisation Min</label><input type=\"number\" id=\"idle_stab_min\" value=\"0\" step=\"1\" min=\"0\" max=\"60\"></div>"
"<div class=\"form-group\"><label>Idle Stabilisation Sec</label><input type=\"number\" id=\"idle_stab_sec\" value=\"5\" step=\"1\" min=\"0\" max=\"59\"></div>"
"</div>"
"<div class=\"form-group\"><label>Proximity</label><div class=\"cb-row\">"
"<label class=\"cbl\"><input type=\"radio\" name=\"proxy_source\" id=\"proxy_en_1\" value=\"1\">Port1</label>"
"<label class=\"cbl\"><input type=\"radio\" name=\"proxy_source\" id=\"proxy_en_2\" value=\"2\">Port2</label>"
"</div></div>"
"<div class=\"form-group checkbox-group\"><input type=\"checkbox\" id=\"encoder_enabled\" onchange=\"toggleEncFields()\"><label for=\"encoder_enabled\">Encoder Input</label></div>"
"<div id=\"enc_fields\" class=\"hidden\"><div class=\"form-row\">"
"<div class=\"form-group\"><label>PPR</label><input type=\"number\" id=\"encoder_ppr\" value=\"600\" step=\"1\"></div>"
"<div class=\"form-group\"><label>MPM Factor</label><input type=\"number\" id=\"encoder_mpm_factor\" value=\"1.0\" step=\"0.001\"></div>"
"</div></div>"
"</div></div>"

"<div class=\"section collapsible collapsed\" id=\"comm_section\">"
"<h2 onclick=\"toggleSection('comm_section')\">Communication <span class=\"toggle\">+</span></h2>"
"<div class=\"section-content\">"
"<div class=\"form-group\"><label>Uplink Mode</label><select id=\"uplink_mode\">"
"<option value=\"0\">WiFi</option><option value=\"1\">LTE (UART)</option></select></div>"
"<div class=\"form-row\">"
"<div class=\"form-group\"><label>Keepalive (s)</label><input type=\"number\" id=\"mqtt_keepalive\" value=\"60\" min=\"1\" max=\"120\"></div>"
"<div class=\"form-group\"><label>Livedata (ms)</label><input type=\"number\" id=\"livedata_interval_ms\" value=\"60000\" step=\"100\" min=\"100\"></div>"
"</div>"
"<div class=\"form-group\"><label>AP SSID Prefix</label><input type=\"text\" id=\"softap_ssid_prefix\" value=\"CT-HMI-\" maxlength=\"17\"></div>"
"</div></div>"

"<button type=\"button\" id=\"save_btn\" class=\"btn-full\" onclick=\"saveConfig()\">Save & Connect</button>"

"<div class=\"status-bar\">"
"<span id=\"status_text\">Ready</span>"
"<span id=\"mac_address\">MAC: Loading...</span>"
"</div>"
"</div>"

"<script>"
"function toggleSection(id){"
"var s=document.getElementById(id);"
"s.classList.toggle('collapsed');"
"s.querySelector('.toggle').textContent=s.classList.contains('collapsed')?'+':'-';"
"}"

"function togglePassword(id,btn){"
"var input=document.getElementById(id);"
"if(input.type==='password'){input.type='text';btn.textContent='Hide';}"
"else{input.type='password';btn.textContent='Show';}"
"}"

"function toggleMqttFields(){"
"var cb=document.getElementById('use_default_mqtt');"
"var fields=document.getElementById('mqtt_fields');"
"if(cb.checked){fields.classList.add('hidden');}"
"else{fields.classList.remove('hidden');}"
"}"

"function toggleEncFields(){"
"var cb=document.getElementById('encoder_enabled');"
"var f=document.getElementById('enc_fields');"
"if(cb.checked){f.classList.remove('hidden');}else{f.classList.add('hidden');}"
"}"

"function updateUplinkModeUI(){"
"var mode=parseInt(document.getElementById('uplink_mode').value)||0;"
"var wifi=document.getElementById('wifi_section');"
"var scan=document.getElementById('scan_btn');"
"if(mode===1){wifi.classList.add('hidden');if(scan)scan.disabled=true;}"
"else{wifi.classList.remove('hidden');if(scan)scan.disabled=false;}"
"}"

"function showAlert(msg,type){"
"var alert=document.getElementById('alert');"
"alert.textContent=msg;"
"alert.className='alert alert-'+type;"
"alert.classList.remove('hidden');"
"setTimeout(function(){alert.classList.add('hidden');},5000);"
"}"

"function setStatus(text,cls){"
"var s=document.getElementById('status_text');"
"s.textContent=text;"
"s.className=cls||'';"
"}"

"function setLoading(btn,loading){"
"if(loading){"
"btn.disabled=true;"
"btn.dataset.text=btn.textContent;"
"btn.innerHTML='<span class=\"loading\"></span>Saving...';"
"}else{"
"btn.disabled=false;"
"btn.textContent=btn.dataset.text||'Save & Connect';"
"}"
"}"

"function loadConfig(){"
"setStatus('Loading config...');"
"fetch('/config')"
".then(r=>r.json())"
".then(data=>{"
"document.getElementById('device_id').value=data.device_id||'';"
"document.getElementById('location').value=data.location||'';"
"document.getElementById('mqtt_broker').value=data.mqtt_broker||'limelight.mvp5464.com';"
"document.getElementById('mqtt_port').value=data.mqtt_port||1883;"
"document.getElementById('mqtt_username').value=data.mqtt_username||'limelightit';"
"document.getElementById('active_threshold').value=data.active_threshold||0.50;"
"if(data.ct_gain&&data.ct_gain.length>=3){"
"document.getElementById('ct_gain_0').value=data.ct_gain[0];"
"document.getElementById('ct_gain_1').value=data.ct_gain[1];"
"document.getElementById('ct_gain_2').value=data.ct_gain[2];"
"}"
"document.getElementById('hysteresis_factor').value=data.hysteresis_factor||0.8;"
"document.getElementById('machine_setup_time_ms').value=data.machine_setup_time_ms||1000;"
"document.getElementById('voltage_nominal').value=data.voltage_nominal||230;"
"document.getElementById('power_factor').value=data.power_factor||0.85;"
"document.getElementById('ignore_open_ct').checked=data.ignore_open_ct!==false;"
"document.getElementById('state_source').value=(data.state_source===undefined)?0:data.state_source;"
"document.getElementById('signal_logic').value=(data.signal_logic===undefined)?0:data.signal_logic;"
"document.getElementById('state_ct_phase_mode').value=(data.state_ct_phase_mode===undefined)?1:data.state_ct_phase_mode;"
"document.getElementById('energy_ct_phase_mode').value=(data.energy_ct_phase_mode===undefined)?1:data.energy_ct_phase_mode;"
"var idleStabMs=data.state_idle_stabilization_ms||5000;"
"var idleStabS=Math.floor(idleStabMs/1000);"
"document.getElementById('idle_stab_min').value=Math.floor(idleStabS/60);"
"document.getElementById('idle_stab_sec').value=idleStabS%60;"
"var pm=(data.proxy_enabled_mask===undefined)?1:data.proxy_enabled_mask;"
"document.getElementById('proxy_en_1').checked=(pm&1)>0;"
"document.getElementById('proxy_en_2').checked=(pm&2)>0;"
"document.getElementById('encoder_enabled').checked=data.encoder_enabled!==false;"
"document.getElementById('encoder_ppr').value=data.encoder_ppr||600;"
"document.getElementById('encoder_mpm_factor').value=data.encoder_mpm_factor||1.0;"
"toggleEncFields();"
"document.getElementById('uplink_mode').value=data.uplink_mode||0;"
"updateUplinkModeUI();"
"if((parseInt(document.getElementById('uplink_mode').value)||0)===0){setTimeout(scanNetworks,200);}"
"document.getElementById('mqtt_keepalive').value=data.mqtt_keepalive||60;"
"document.getElementById('livedata_interval_ms').value=data.livedata_interval_ms||60000;"
"document.getElementById('softap_ssid_prefix').value=data.softap_ssid_prefix||'CT-HMI-';"
"document.getElementById('mac_address').textContent='MAC: '+data.mac_address;"
"if(data.wifi_ssid){"
"var sel=document.getElementById('wifi_ssid');"
"var opt=document.createElement('option');"
"opt.value=data.wifi_ssid;opt.textContent=data.wifi_ssid+' (saved)';"
"sel.appendChild(opt);sel.value=data.wifi_ssid;"
"}"
"setStatus('Ready','ok');"
"})"
".catch(e=>{"
"setStatus('Error loading config','warn');"
"console.error(e);"
"});"
"}"

"function scanNetworks(){"
"if((parseInt(document.getElementById('uplink_mode').value)||0)===1){return;}"
"var btn=document.getElementById('scan_btn');"
"var sel=document.getElementById('wifi_ssid');"
"var current=sel.value;"
"btn.disabled=true;btn.textContent='Scanning...';"
"sel.innerHTML='<option value=\"\">Scanning...</option>';"
"fetch('/scan')"
".then(r=>r.json())"
".then(data=>{"
"sel.innerHTML='<option value=\"\">-- Select Network --</option>';"
"if(data.networks&&data.networks.length>0){"
"data.networks.forEach(n=>{"
"var opt=document.createElement('option');"
"opt.value=n.ssid;"
"opt.textContent=n.ssid+' ('+n.rssi+'dBm, '+n.auth+')';"
"sel.appendChild(opt);"
"});"
"if(current){sel.value=current;}"
"}else{"
"sel.innerHTML='<option value=\"\">No networks found</option>';"
"}"
"btn.disabled=false;btn.textContent='Scan';"
"})"
".catch(e=>{"
"sel.innerHTML='<option value=\"\">Scan failed</option>';"
"btn.disabled=false;btn.textContent='Scan';"
"console.error(e);"
"});"
"}"

"function saveConfig(){"
"var device_id=document.getElementById('device_id').value.trim();"
"var wifi_ssid=document.getElementById('wifi_ssid').value;"
"var wifi_password=document.getElementById('wifi_password').value;"
"var uplink_mode=parseInt(document.getElementById('uplink_mode').value)||0;"
"if(!device_id){showAlert('Device ID is required','error');return;}"
"if(uplink_mode===0&&!wifi_ssid){showAlert('Please select a WiFi network','error');return;}"
"if(uplink_mode===0&&!wifi_password){showAlert('WiFi password is required','error');return;}"
"var pm=document.getElementById('proxy_en_2').checked?2:1;"
"var idleMin=parseInt(document.getElementById('idle_stab_min').value)||0;"
"var idleSec=parseInt(document.getElementById('idle_stab_sec').value)||0;"
"var idleTotalSec=idleMin*60+idleSec;"
"if(idleTotalSec<1||idleTotalSec>3600){showAlert('Idle stabilisation must be 1s to 60min','error');return;}"
"var config={"
"device_id:device_id,"
"location:document.getElementById('location').value.trim(),"
"mqtt_broker:document.getElementById('mqtt_broker').value,"
"mqtt_port:parseInt(document.getElementById('mqtt_port').value)||1883,"
"mqtt_username:document.getElementById('mqtt_username').value,"
"mqtt_password:document.getElementById('mqtt_password').value,"
"active_threshold:parseFloat(document.getElementById('active_threshold').value)||0.50,"
"ct_gain:["
"parseFloat(document.getElementById('ct_gain_0').value)||1.314,"
"parseFloat(document.getElementById('ct_gain_1').value)||1.314,"
"parseFloat(document.getElementById('ct_gain_2').value)||1.314"
"],"
"hysteresis_factor:parseFloat(document.getElementById('hysteresis_factor').value)||0.8,"
"machine_setup_time_ms:parseInt(document.getElementById('machine_setup_time_ms').value)||1000,"
"voltage_nominal:parseFloat(document.getElementById('voltage_nominal').value)||230,"
"power_factor:parseFloat(document.getElementById('power_factor').value)||0.85,"
"ct_enabled_mask:7,"
"ignore_open_ct:document.getElementById('ignore_open_ct').checked,"
"state_source:parseInt(document.getElementById('state_source').value)||0,"
"signal_logic:parseInt(document.getElementById('signal_logic').value)||0,"
"state_ct_phase_mode:parseInt(document.getElementById('state_ct_phase_mode').value)||0,"
"energy_ct_phase_mode:parseInt(document.getElementById('energy_ct_phase_mode').value)||0,"
"state_idle_stabilization_ms:idleTotalSec*1000,"
"proxy_enabled_mask:pm,"
"encoder_enabled:document.getElementById('encoder_enabled').checked,"
"encoder_ppr:parseFloat(document.getElementById('encoder_ppr').value)||600,"
"encoder_mpm_factor:parseFloat(document.getElementById('encoder_mpm_factor').value)||1.0,"
"uplink_mode:uplink_mode,"
"mqtt_keepalive:parseInt(document.getElementById('mqtt_keepalive').value)||60,"
"livedata_interval_ms:parseInt(document.getElementById('livedata_interval_ms').value)||60000,"
"softap_ssid_prefix:document.getElementById('softap_ssid_prefix').value||'CT-HMI-'"
"};"
"if(uplink_mode===0){config.wifi_ssid=wifi_ssid;config.wifi_password=wifi_password;}"
"var btn=document.getElementById('save_btn');"
"setLoading(btn,true);"
"setStatus('Saving configuration...');"
"fetch('/config',{"
"method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(config)"
"})"
".then(r=>r.json())"
".then(data=>{"
"if(data.success){"
"showAlert('Configuration saved! Device will reboot in 3 seconds...','success');"
"setStatus('Saved! Rebooting...','ok');"
"setTimeout(function(){"
"document.body.innerHTML='<div style=\"text-align:center;padding:50px;\">"
"<h2>Configuration Saved</h2>"
"<p>Device is rebooting...</p>"
"<p>Device will reconnect using the selected uplink.</p>"
"</div>';"
"},3000);"
"}else{"
"showAlert(data.error||'Failed to save configuration','error');"
"setLoading(btn,false);"
"setStatus('Save failed','warn');"
"}"
"})"
".catch(e=>{"
"showAlert('Error saving configuration','error');"
"setLoading(btn,false);"
"setStatus('Error','warn');"
"console.error(e);"
"});"
"}"

"document.addEventListener('DOMContentLoaded',function(){"
"loadConfig();"
"document.getElementById('uplink_mode').addEventListener('change',updateUplinkModeUI);"
"document.getElementById('scan_btn').addEventListener('click',scanNetworks);"
"});"
"</script>"
"</body>"
"</html>";

const char* web_content_get_index_html(void)
{
    return INDEX_HTML;
}

size_t web_content_get_index_html_len(void)
{
    return sizeof(INDEX_HTML) - 1;  // Exclude null terminator
}
